# Lecture 1 : Getting started with Numpy

In [ ]:
import numpy as np

In [ ]:
np

<module 'numpy' from '/usr/local/lib/python3.7/dist-packages/numpy/__init__.py'>

In [ ]:
l = [[1,2,3.0],[2,3,4]]
l

[[1, 2, 3.0], [2, 3, 4]]

In [ ]:
a = np.array(l)
a

array([[1., 2., 3.],
       [2., 3., 4.]])

In [ ]:
print(type(l),type(a))

<class 'list'> <class 'numpy.ndarray'>


In [ ]:
a.ndim

2

In [ ]:
a.shape

(2, 3)

In [ ]:
a.size

6

In [ ]:
a.dtype

dtype('float64')

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#Lecture 2: Reshape and Random Number Generator

In [ ]:
import numpy as np

In [ ]:
np.random.random((3,4))

array([[0.77793267, 0.67495697, 0.78660718, 0.77984591],
       [0.61682399, 0.66047996, 0.35130563, 0.25850058],
       [0.8819997 , 0.92970957, 0.56851813, 0.97535641]])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.linspace(1,10,9)

array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
       10.   ])

In [ ]:
arr = np.random.random((4,3))
print(arr.shape)
arr_reshaped = arr.reshape((3,4))
print(arr_reshaped.shape)

(4, 3)
(3, 4)


In [ ]:
print(arr,'\n\n',arr_reshaped)

[[0.51192435 0.9367532  0.59716102]
 [0.2266606  0.12793979 0.19970944]
 [0.22542829 0.86835293 0.36001988]
 [0.5169844  0.50902601 0.36648509]] 

 [[0.51192435 0.9367532  0.59716102 0.2266606 ]
 [0.12793979 0.19970944 0.22542829 0.86835293]
 [0.36001988 0.5169844  0.50902601 0.36648509]]


In [ ]:
arr.flatten()

array([0.51192435, 0.9367532 , 0.59716102, 0.2266606 , 0.12793979,
       0.19970944, 0.22542829, 0.86835293, 0.36001988, 0.5169844 ,
       0.50902601, 0.36648509])

# Lecture 3: Arithmetic Operations on Array

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5,6])

In [ ]:
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
a+1

array([2, 3, 4, 5, 6, 7])

In [ ]:
a*2

array([ 2,  4,  6,  8, 10, 12])

In [ ]:
a-2

array([-1,  0,  1,  2,  3,  4])

In [ ]:
a/0.5

array([ 2.,  4.,  6.,  8., 10., 12.])

In [ ]:
a.max()

6

In [ ]:
a.min()

1

In [ ]:
ar = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

In [16]:
ar.max()

9

In [17]:
ar.max(axis=0)

array([7, 8, 9])

In [18]:
ar.max(axis=1)

array([3, 6, 9])

In [20]:
ar.sum()

45

In [22]:
ar.sum(axis=0)

array([12, 15, 18])

In [23]:
ar.sum(axis=1)

array([ 6, 15, 24])

# Lecture 4: Arithmetic Operations on Multiple Arrays

In [24]:
import numpy as np

In [25]:
arr1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
arr2 = np.array([[9,8,7],
                 [6,5,4],
                 [3,2,1]])

In [26]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
arr2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [28]:
arr1+arr2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [29]:
arr1*arr2

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [30]:
arr1.dot(arr2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [31]:
arr2.dot(arr1)

array([[ 90, 114, 138],
       [ 54,  69,  84],
       [ 18,  24,  30]])

In [35]:
arr1[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [40]:
arr1[:][1:]

array([[4, 5, 6],
       [7, 8, 9]])

# Lecture 5: Array Sorting

In [41]:
import numpy as np

In [43]:
arr = np.array([[3,2,5,8,9],
                 [7,2,9,8,6],
                 [5,4,2,3,1]])

In [44]:
np.sort(arr, axis=0)

array([[3, 2, 2, 3, 1],
       [5, 2, 5, 8, 6],
       [7, 4, 9, 8, 9]])

In [47]:
np.sort(arr,axis=1,kind='mergesort')

array([[2, 3, 5, 8, 9],
       [2, 6, 7, 8, 9],
       [1, 2, 3, 4, 5]])

In [48]:
np.sort(arr)

array([[2, 3, 5, 8, 9],
       [2, 6, 7, 8, 9],
       [1, 2, 3, 4, 5]])

# Lecture 6: Array Slicing

In [49]:
import numpy as np

In [51]:
arr1 = np.array([2,3,4,5,6,7,8])

In [52]:
arr2 = np.array([[1,2,3,4],[5,6,7,8],[8,7,6,5],[4,3,2,1]])

In [53]:
arr1[:3]

array([2, 3, 4])

In [54]:
arr2[:3]

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5]])

In [55]:
arr2[:3,1:]

array([[2, 3, 4],
       [6, 7, 8],
       [7, 6, 5]])

In [56]:
arr1[::-1]

array([8, 7, 6, 5, 4, 3, 2])

In [57]:
arr1[None:1]

array([2])

# Lecture 7: Array Merging

In [58]:
import numpy as np

In [60]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
arr2 = np.array([[8,7,6,5],[4,3,2,1]])

In [64]:
np.vstack((arr1,arr2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [65]:
np.hstack((arr1,arr2))

array([[1, 2, 3, 4, 8, 7, 6, 5],
       [5, 6, 7, 8, 4, 3, 2, 1]])

In [66]:
np.concatenate((arr1,arr2),axis=0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [67]:
np.concatenate((arr1,arr2),axis=1)

array([[1, 2, 3, 4, 8, 7, 6, 5],
       [5, 6, 7, 8, 4, 3, 2, 1]])

In [73]:
np.vsplit(arr1,2)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

In [74]:
np.hsplit(arr1,4)

[array([[1],
        [5]]), array([[2],
        [6]]), array([[3],
        [7]]), array([[4],
        [8]])]

# Lecture 8: Automate using Numpy

In [75]:
import numpy as np

In [80]:
l = [i for i in range(1,11)]

In [81]:
l

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [82]:
q = 0
for i in l:
  if i>5:
    q+=1
print(q)

5


In [83]:
l_arr = np.array(l)

In [84]:
l_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
len(l_arr[l_arr>5])

5

In [87]:
len(l_arr[l_arr%3==0])

3

In [88]:
l_arr[l_arr%3==0]

array([3, 6, 9])